### PR TITLE
Modificacion de SSPP-EBD diagrama logico y fisico

### PR DESCRIPTION
**Pull request by GianAle1**
Modificacion de SSPP-EBD diagrama logico y fisico

### CODE REVIEW

**Comment by GianAle1** [comment]
s

**Comment by GianAle1** [comment]
s

**Review by GianAle1 — COMMENTED** [review]
.

**Comment by RawlV** [comment]
git pull origin main
[SSPP-EBD.docx](https://github.com/GianAle1/TSKC/files/11525056/SSPP-EBD.docx)

**Comment by RawlV** [comment]
git pull origin main

**Pull request closed without merging**
